import JSZip from 'jszip'
import type { AppConfig } from './types'

function slugify(name: string) {
  return name.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'web-app'
}

export async function downloadProject(config: AppConfig, iconDataUrl?: string) {
  const slug = slugify(config.appName)
  const zip = new JSZip()
  const root = zip.folder(slug)!
  const tauri = root.folder('src-tauri')!
  const src = tauri.folder('src')!

  root.file('package.json', JSON.stringify({
    name: slug,
    private: true,
    version: '0.1.0',
    scripts: { tauri: 'tauri' },
    devDependencies: { '@tauri-apps/cli': '^2.0.0' },
  }, null, 2))
  const androidGuide = config.platforms.includes('android')
    ? '\n## Android APK\n\n1. Install Android Studio, SDK/NDK, Java, and the Rust Android targets.\n2. Run `npm run tauri -- android init`.\n3. Run `npm run tauri -- android build --apk`.\n'
    : ''
  root.file('README.md', `# ${config.appName}\n\nGenerated by Web2App Studio.\n\n## Desktop build\n\n1. Install the Tauri prerequisites for your operating system.\n2. Run \`npm install\`.\n3. Run \`npm run tauri build\`.\n\nBuild each desktop target on its native operating system or use a CI matrix.\n${androidGuide}`)
  tauri.file('build.rs', 'fn main() { tauri_build::build() }\n')
  tauri.file('Cargo.toml', `[package]\nname = "${slug.replaceAll('-', '_')}"\nversion = "0.1.0"\ndescription = "${config.appName}"\nedition = "2021"\n\n[lib]\nname = "app_lib"\ncrate-type = ["staticlib", "cdylib", "rlib"]\n\n[build-dependencies]\ntauri-build = { version = "2", features = [] }\n\n[dependencies]\ntauri = { version = "2", features = [] }\n`)
  src.file('main.rs', `#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]\n\nfn main() {\n  app_lib::run();\n}\n`)
  src.file('lib.rs', `#[cfg_attr(mobile, tauri::mobile_entry_point)]\npub fn run() {\n  tauri::Builder::default()\n    .run(tauri::generate_context!())\n    .expect("error while running the application");\n}\n`)
  tauri.file('tauri.conf.json', JSON.stringify({
    $schema: 'https://schema.tauri.app/config/2',
    productName: config.appName,
    version: '0.1.0',
    identifier: `app.web2app.${slug.replaceAll('-', '')}`,
    build: {},
    app: {
      windows: [{
        label: 'main',
        title: config.appName,
        url: config.url,
        width: config.width,
        height: config.height,
        minWidth: 480,
        minHeight: 360,
        resizable: config.resizable,
        alwaysOnTop: config.alwaysOnTop,
        center: true,
      }],
      security: { csp: null },
    },
    bundle: {
      active: true,
      targets: 'all',
      ...(iconDataUrl ? { icon: ['icons/icon.png'] } : {}),
    },
  }, null, 2))
  if (iconDataUrl) {
    tauri.file('icons/icon.png', iconDataUrl.split(',')[1], { base64: true })
  }
  root.file('web2app.config.json', JSON.stringify(config, null, 2))

  const blob = await zip.generateAsync({ type: 'blob' })
  const href = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = href
  anchor.download = `${slug}-tauri.zip`
  anchor.click()
  URL.revokeObjectURL(href)
}

export async function downloadAndroidApk(config: AppConfig, iconDataUrl?: string) {
  const response = await fetch('/api/build/android', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ config, iconDataUrl }),
  })
  if (!response.ok) {
    const result = await response.json().catch(() => null)
    throw new Error(result?.message || 'APK 构建失败，请检查构建服务。')
  }
  const blob = await response.blob()
  const href = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = href
  anchor.download = `${slugify(config.appName)}.apk`
  anchor.click()
  URL.revokeObjectURL(href)
}
